#!/usr/bin/env python3
"""
seed_timetable.py
-----------------
Seeds the timetables table interactively or programmatically.
Creates the table if not present, and populates it with sample data.
"""

import sys
import signal
import os
import argparse
from datetime import datetime, timedelta
from colorama import Fore, Style, init
from configparser import ConfigParser
from dotenv import load_dotenv
from sqlalchemy import create_engine, Table, MetaData
from sqlalchemy.orm import sessionmaker
from sqlalchemy.exc import IntegrityError

init(autoreset=True)

# DB Configuration using .env and config.ini
def load_configuration():
    """Load configuration from .env and config.ini."""
    load_dotenv()  # Load .env file

    # Load PostgreSQL settings from config.ini
    config = ConfigParser()
    config.read('config.ini')

    db_config = config['postgres']
    db_url = f"postgresql://{db_config['host']}:{db_config['port']}/{db_config['default_db']}"
    
    return db_url

# Establish connection to the DB
def get_db_session():
    """Establishes a new DB session using the loaded DB URL."""
    db_url = load_configuration()
    engine = create_engine(db_url, echo=False, future=True)
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    db = SessionLocal()
    return db

# Helper function to check if a table exists
def table_exists(db, table_name):
    """Check if the given table exists in the database."""
    metadata = MetaData(bind=db.bind)
    return Table(table_name, metadata, autoload_with=db.bind).exists()

# Insert operation
def insert(db, table_name, data, id_column="id"):
    """Inserts data into the given table."""
    try:
        db.execute(table_name.insert().values(data))
        db.commit()
    except IntegrityError as e:
        db.rollback()
        raise e

# Update operation
def update(db, table_name, data, condition):
    """Update data in the table based on condition."""
    db.execute(table_name.update().where(condition).values(data))
    db.commit()

# Select operation
def select(db, table_name, fields="*", condition=None):
    """Select records from a table based on condition."""
    if condition:
        return db.execute(table_name.select().where(condition)).fetchall()
    return db.execute(table_name.select().with_only_columns(fields)).fetchall()

# Graceful exit for script
def graceful_exit(sig, frame):
    print("\nExiting gracefully. Goodbye!")
    sys.exit(0)

# Handle Ctrl+C and Ctrl+X
signal.signal(signal.SIGINT, graceful_exit)   # Ctrl+C
signal.signal(signal.SIGTERM, graceful_exit)  # Ctrl+X

def write_timetables_sql(timetables, csv_path):
    """Generate timetables.sql next to the loaded CSV file."""
    out_dir = os.path.dirname(csv_path)
    out_path = os.path.join(out_dir, "timetables.sql")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("-- timetables.sql\n")
        f.write("-- Auto-generated by seed_timetable.py\n\n")
        f.write("CREATE TABLE IF NOT EXISTS timetables (\n")
        f.write("    timetable_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n")
        f.write("    vehicle_id   uuid NOT NULL,\n")
        f.write("    route_id     uuid NOT NULL,\n")
        f.write("    departure_time timestamptz NOT NULL,\n")
        f.write("    arrival_time   timestamptz,\n")
        f.write("    notes        text,\n")
        f.write("    created_at   timestamptz NOT NULL DEFAULT now(),\n")
        f.write("    updated_at   timestamptz NOT NULL DEFAULT now()\n")
        f.write(");\n\n")

        f.write("INSERT INTO timetables (vehicle_id, route_id, departure_time, arrival_time, notes) VALUES\n")

        rows = []
        for row in timetables:
            vehicle_id = row["vehicle_id"]
            route_id = row["route_id"]
            dep_time = row["departure_time"]
            arr_time = row["arrival_time"]
            notes = row["notes"].replace("'", "''")
            rows.append(f"    ('{vehicle_id}', '{route_id}', '{dep_time}', '{arr_time}', '{notes}')")

        f.write(",\n".join(rows))
        f.write("\nON CONFLICT (vehicle_id, route_id, departure_time) DO UPDATE SET arrival_time = EXCLUDED.arrival_time;\n")

    return out_path

def generate_timetable_data():
    """Generate or load timetable data."""
    # Sample data (replace with real-world data or files as needed)
    timetables = []
    vehicles = ["19c7a341-5fb9-4ad6-b08c-3fd2b3fefe2c", "19c7a341-5fb9-4ad6-b08c-3fd2b3fefe2d"]  # Example vehicle UUIDs
    routes = ["14aba2e0-8c5e-40f3-9fea-b4f740c7f7a3", "14aba2e0-8c5e-40f3-9fea-b4f740c7f7a4"]  # Example route UUIDs
    for i in range(2):
        departure_time = datetime.utcnow() + timedelta(minutes=i * 30)
        arrival_time = departure_time + timedelta(minutes=60)  # Example 1-hour trip
        timetables.append({
            "vehicle_id": vehicles[i],
            "route_id": routes[i],
            "departure_time": departure_time.isoformat(),
            "arrival_time": arrival_time.isoformat(),
            "notes": f"Test trip {i+1}"
        })
    return timetables

def seed_timetable(interactive: bool = True):
    """
    Seed the timetables table.
    - interactive=True: prints help, prompts user, prints row-by-row feedback
    - interactive=False: runs silently, just returns summary dict
    Returns: dict with inserted/updated/skipped/sql_file
    """
    config = load_configuration()  # Load configuration using the new method
    result = {"inserted": 0, "updated": 0, "skipped": 0, "sql_file": None}

    with get_db_session() as db:
        if interactive:
            print(get_help_text())

        # Ensure table exists
        if not table_exists(db, "timetables"):
            if interactive:
                print("[INFO] Timetables table not found, creating...")
            schema_sql = """
            CREATE TABLE timetables (
                timetable_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                vehicle_id   uuid NOT NULL,
                route_id     uuid NOT NULL,
                departure_time timestamptz NOT NULL,
                arrival_time   timestamptz,
                notes        text,
                created_at   timestamptz NOT NULL DEFAULT now(),
                updated_at   timestamptz NOT NULL DEFAULT now()
            );
            """
            create_table(db, schema_sql)

        timetables = generate_timetable_data()

        # Check if already populated
        existing = select(db, "timetables", "count(*) as count")[0]["count"]

        if interactive and existing > 0:
            choice = input("[?] Timetables table already contains data. Update it? (Y/n, S=skip): ").strip().lower()
            if choice == "s":
                if interactive:
                    print("[INFO] Skipping seeding.")
                return result
            update_mode = (choice == "y")
        else:
            update_mode = existing > 0

        for row in timetables:
            try:
                if update_mode:
                    update(db, "timetables", {"arrival_time": row["arrival_time"]}, {"vehicle_id": row["vehicle_id"], "route_id": row["route_id"], "departure_time": row["departure_time"]})
                    result["updated"] += 1
                    if interactive:
                        print(Fore.GREEN + f"[OK] Updated {row['vehicle_id']} on route {row['route_id']} for departure {row['departure_time']}")
                else:
                    insert(db, "timetables", row, id_column="timetable_id")
                    result["inserted"] += 1
                    if interactive:
                        print(Fore.GREEN + f"[OK] Inserted timetable for {row['vehicle_id']} on route {row['route_id']}")

            except Exception as e:
                result["skipped"] += 1
                if interactive:
                    print(Fore.RED + f"[X] Failed timetable for {row['vehicle_id']} on route {row['route_id']}: {e}")

        # Write SQL file
        sql_path = write_timetables_sql(timetables, config["files"]["timetables"])
        result["sql_file"] = sql_path

        if interactive:
            print(Style.BRIGHT + f"\nSummary: Inserted={result['inserted']}, Updated={result['updated']}, Skipped={result['skipped']}")
            print(Fore.GREEN + f"[OK] Generated {sql_path}")

    return result

def get_help_text():
    return """
    [Help Menu]
    - This script will seed the timetables table in your database.
    - Available options:
      - Interactive mode (default): Asks for confirmation before inserting or updating timetables.
      - Silent mode: Runs without asking and just populates the table.
    - Use -h or --help to show this help menu.
    """

if __name__ == "__main__":
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("-h", "--help", action="store_true", help="Show help menu and exit")
    args = parser.parse_args()

    if args.help:
        print(get_help_text())
        sys.exit(0)

    summary = seed_timetable(interactive=True)
    print(summary)  # Debug summary dict
