-- Auto-generated by seed_timetable.py

CREATE TABLE IF NOT EXISTS timetables (
  timetable_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id   uuid NOT NULL,
  route_id     uuid NOT NULL,
  departure_time timestamptz NOT NULL,
  arrival_time   timestamptz,
  notes        text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

INSERT INTO timetables (vehicle_id, route_id, departure_time, arrival_time, notes) VALUES
  ('19c7a341-5fb9-4ad6-b08c-3fd2b3fefe2c', '14aba2e0-8c5e-40f3-9fea-b4f740c7f7a3', '2025-09-06T07:51:51.220531Z', '2025-09-06T08:51:51.220531Z', 'Test trip 1'),
  ('19c7a341-5fb9-4ad6-b08c-3fd2b3fefe2d', '14aba2e0-8c5e-40f3-9fea-b4f740c7f7a4', '2025-09-06T08:21:51.225066Z', '2025-09-06T09:21:51.225066Z', 'Test trip 2');
