"""add_gps_devices_and_vehicle_gps_assignment

Revision ID: 2ec964fc3bef
Revises: abc123456789
Create Date: 2025-09-12 21:17:10.783770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec964fc3bef'
down_revision: Union[str, Sequence[str], None] = 'abc123456789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_devices',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.Text(), nullable=False),
    sa.Column('serial_number', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('firmware_version', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('device_name'),
    sa.UniqueConstraint('serial_number')
    )
    op.alter_column('routes', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(length=7),
               existing_nullable=True)
    op.add_column('vehicles', sa.Column('assigned_gps_device_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'gps_devices', ['assigned_gps_device_id'], ['device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'assigned_gps_device_id')
    op.alter_column('routes', 'color',
               existing_type=sa.String(length=7),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('gps_devices')
    # ### end Alembic commands ###
