// Seed script for AccessTier table in Strapi
// Run with: node scripts/seed_access_tiers.js

const { Client } = require('pg');

const client = new Client({
  host: '127.0.0.1',
  port: 5432,
  database: 'arknettransit',
  user: 'david',
  password: 'Ga25w123!'
});

const tiers = [
  { 
    name: 'Manager', 
    code: 'manager', 
    level: 4,
    description: 'Management access', 
    can_manage_autostart: true, 
    can_view_services: true, 
    can_create_users: false, 
    can_manage_all_autostart: false,
    can_create_access_tier: false,
    can_read_access_tier: false,
    can_update_access_tier: false,
    can_delete_access_tier: false,
    can_create_user_profile: true,
    can_read_user_profile: true,
    can_update_user_profile: true,
    can_delete_user_profile: false,
    can_create_agency: true,
    can_read_agency: true,
    can_update_agency: true,
    can_delete_agency: false,
    can_create_vehicle: true,
    can_read_vehicle: true,
    can_update_vehicle: true,
    can_delete_vehicle: false,
    can_create_route: true,
    can_read_route: true,
    can_update_route: true,
    can_delete_route: false
  },
  { 
    name: 'Dispatcher', 
    code: 'dispatcher', 
    level: 3,
    description: 'Dispatcher access', 
    can_manage_autostart: true, 
    can_view_services: true, 
    can_create_users: false, 
    can_manage_all_autostart: false,
    can_create_access_tier: false,
    can_read_access_tier: false,
    can_update_access_tier: false,
    can_delete_access_tier: false,
    can_create_user_profile: false,
    can_read_user_profile: true,
    can_update_user_profile: false,
    can_delete_user_profile: false,
    can_create_agency: false,
    can_read_agency: true,
    can_update_agency: false,
    can_delete_agency: false,
    can_create_vehicle: false,
    can_read_vehicle: true,
    can_update_vehicle: false,
    can_delete_vehicle: false,
    can_create_route: false,
    can_read_route: true,
    can_update_route: false,
    can_delete_route: false
  },
  { 
    name: 'Operator', 
    code: 'operator', 
    level: 2,
    description: 'Operational access', 
    can_manage_autostart: true, 
    can_view_services: true, 
    can_create_users: false, 
    can_manage_all_autostart: false,
    can_create_access_tier: false,
    can_read_access_tier: false,
    can_update_access_tier: false,
    can_delete_access_tier: false,
    can_create_user_profile: false,
    can_read_user_profile: true,
    can_update_user_profile: false,
    can_delete_user_profile: false,
    can_create_agency: false,
    can_read_agency: true,
    can_update_agency: false,
    can_delete_agency: false,
    can_create_vehicle: false,
    can_read_vehicle: true,
    can_update_vehicle: true,
    can_delete_vehicle: false,
    can_create_route: false,
    can_read_route: true,
    can_update_route: true,
    can_delete_route: false
  },
  { 
    name: 'Viewer', 
    code: 'viewer', 
    level: 1,
    description: 'Read-only access', 
    can_manage_autostart: false, 
    can_view_services: true, 
    can_create_users: false, 
    can_manage_all_autostart: false,
    can_create_access_tier: false,
    can_read_access_tier: false,
    can_update_access_tier: false,
    can_delete_access_tier: false,
    can_create_user_profile: false,
    can_read_user_profile: true,
    can_update_user_profile: false,
    can_delete_user_profile: false,
    can_create_agency: false,
    can_read_agency: true,
    can_update_agency: false,
    can_delete_agency: false,
    can_create_vehicle: false,
    can_read_vehicle: true,
    can_update_vehicle: false,
    can_delete_vehicle: false,
    can_create_route: false,
    can_read_route: true,
    can_update_route: false,
    can_delete_route: false
  },
  { 
    name: 'Admin', 
    code: 'admin', 
    level: 5,
    description: 'Full access', 
    can_manage_autostart: true, 
    can_view_services: true, 
    can_create_users: true, 
    can_manage_all_autostart: true,
    can_create_access_tier: false,
    can_read_access_tier: true,
    can_update_access_tier: false,
    can_delete_access_tier: false,
    can_create_user_profile: true,
    can_read_user_profile: true,
    can_update_user_profile: true,
    can_delete_user_profile: true,
    can_create_agency: true,
    can_read_agency: true,
    can_update_agency: true,
    can_delete_agency: true,
    can_create_vehicle: true,
    can_read_vehicle: true,
    can_update_vehicle: true,
    can_delete_vehicle: true,
    can_create_route: true,
    can_read_route: true,
    can_update_route: true,
    can_delete_route: true
  },
  { 
    name: 'Guest', 
    code: 'guest', 
    level: 0,
    description: 'Limited access', 
    can_manage_autostart: false, 
    can_view_services: false, 
    can_create_users: false, 
    can_manage_all_autostart: false,
    can_create_access_tier: false,
    can_read_access_tier: false,
    can_update_access_tier: false,
    can_delete_access_tier: false,
    can_create_user_profile: false,
    can_read_user_profile: false,
    can_update_user_profile: false,
    can_delete_user_profile: false,
    can_create_agency: false,
    can_read_agency: false,
    can_update_agency: false,
    can_delete_agency: false,
    can_create_vehicle: false,
    can_read_vehicle: false,
    can_update_vehicle: false,
    can_delete_vehicle: false,
    can_create_route: false,
    can_read_route: false,
    can_update_route: false,
    can_delete_route: false
  },
  { 
    name: 'SuperAdmin', 
    code: 'superadmin', 
    level: 6,
    description: 'Super admin access', 
    can_manage_autostart: true, 
    can_view_services: true, 
    can_create_users: true, 
    can_manage_all_autostart: true,
    can_create_access_tier: true,
    can_read_access_tier: true,
    can_update_access_tier: true,
    can_delete_access_tier: true,
    can_create_user_profile: true,
    can_read_user_profile: true,
    can_update_user_profile: true,
    can_delete_user_profile: true,
    can_create_agency: true,
    can_read_agency: true,
    can_update_agency: true,
    can_delete_agency: true,
    can_create_vehicle: true,
    can_read_vehicle: true,
    can_update_vehicle: true,
    can_delete_vehicle: true,
    can_create_route: true,
    can_read_route: true,
    can_update_route: true,
    can_delete_route: true
  }
];

async function seed() {
  await client.connect();
  for (const tier of tiers) {
    await client.query(
      `INSERT INTO access_tiers (name, code, level, description, can_manage_autostart, can_view_services, can_create_users, can_manage_all_autostart, can_create_access_tier, can_read_access_tier, can_update_access_tier, can_delete_access_tier, can_create_user_profile, can_read_user_profile, can_update_user_profile, can_delete_user_profile, can_create_agency, can_read_agency, can_update_agency, can_delete_agency, can_create_vehicle, can_read_vehicle, can_update_vehicle, can_delete_vehicle, can_create_route, can_read_route, can_update_route, can_delete_route) 
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28) 
       ON CONFLICT (name) DO UPDATE SET 
         code = EXCLUDED.code, 
         level = EXCLUDED.level,
         description = EXCLUDED.description, 
         can_manage_autostart = EXCLUDED.can_manage_autostart, 
         can_view_services = EXCLUDED.can_view_services, 
         can_create_users = EXCLUDED.can_create_users, 
         can_manage_all_autostart = EXCLUDED.can_manage_all_autostart,
         can_create_access_tier = EXCLUDED.can_create_access_tier,
         can_read_access_tier = EXCLUDED.can_read_access_tier,
         can_update_access_tier = EXCLUDED.can_update_access_tier,
         can_delete_access_tier = EXCLUDED.can_delete_access_tier,
         can_create_user_profile = EXCLUDED.can_create_user_profile,
         can_read_user_profile = EXCLUDED.can_read_user_profile,
         can_update_user_profile = EXCLUDED.can_update_user_profile,
         can_delete_user_profile = EXCLUDED.can_delete_user_profile,
         can_create_agency = EXCLUDED.can_create_agency,
         can_read_agency = EXCLUDED.can_read_agency,
         can_update_agency = EXCLUDED.can_update_agency,
         can_delete_agency = EXCLUDED.can_delete_agency,
         can_create_vehicle = EXCLUDED.can_create_vehicle,
         can_read_vehicle = EXCLUDED.can_read_vehicle,
         can_update_vehicle = EXCLUDED.can_update_vehicle,
         can_delete_vehicle = EXCLUDED.can_delete_vehicle,
         can_create_route = EXCLUDED.can_create_route,
         can_read_route = EXCLUDED.can_read_route,
         can_update_route = EXCLUDED.can_update_route,
         can_delete_route = EXCLUDED.can_delete_route`,
      [tier.name, tier.code, tier.level, tier.description, tier.can_manage_autostart, tier.can_view_services, tier.can_create_users, tier.can_manage_all_autostart, tier.can_create_access_tier, tier.can_read_access_tier, tier.can_update_access_tier, tier.can_delete_access_tier, tier.can_create_user_profile, tier.can_read_user_profile, tier.can_update_user_profile, tier.can_delete_user_profile, tier.can_create_agency, tier.can_read_agency, tier.can_update_agency, tier.can_delete_agency, tier.can_create_vehicle, tier.can_read_vehicle, tier.can_update_vehicle, tier.can_delete_vehicle, tier.can_create_route, tier.can_read_route, tier.can_update_route, tier.can_delete_route]
    );
    console.log(`Seeded: ${tier.name}`);
  }
  await client.end();
  console.log('AccessTier seeding complete.');
}

seed().catch(err => {
  console.error('Seeding error:', err);
  client.end();
});
