"""Initial migration

Revision ID: 15d8f14a1d06
Revises: 
Create Date: 2024-01-18 11:37:28.766066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '15d8f14a1d06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('route_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('shape', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('route_id')
    )
    op.create_table('vehicles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vehicle_id', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('route_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('routes')
    # ### end Alembic commands ###
