"""Add description and color to Route model

Revision ID: b72f0cb20b7f
Revises: f26a154d527c
Create Date: 2025-09-11 20:43:11.134920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72f0cb20b7f'
down_revision: Union[str, Sequence[str], None] = 'f26a154d527c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('routes', sa.Column('color', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'color')
    op.drop_column('routes', 'description')
    # ### end Alembic commands ###
